name: CI

on:
  push:
    branches: master
  pull_request:
    types:
      - assigned
      - labeled
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  build-macos:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        formula:
          - { name: flatcam-beta }
          - { name: flatcam-evo }
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
      - name: Update Homebrew
        run: |
          rm -rf $(brew --repo homebrew/cask)
          rm -rf $(brew --repo homebrew/cask-versions)
          rm -rf $(brew --cellar)/*
          sudo rm -rf /usr/local/include/* /usr/local/lib/*
          brew update-reset
          brew cleanup
      - name: Set up tap
        run: |
          REPO=$(brew --repo ${{github.repository}})
          mkdir -p "$REPO"
          rm -rf "$REPO"
          ln -s $GITHUB_WORKSPACE "$REPO"
      - name: Run brew install # do not test with brew-test-bot but just try to install
        run: brew install ${{ matrix.formula.name }} --debug --verbose
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
